backend/app_setup/urls.py
from app_setup.views import subcontractor, account, subcontractortypes, unit, \
    paypurpose, legalform, taxetype, projectcategory, projectsubcategory, brand, nbsource, \
    nbformat, productcategory, projectproduct, currency, team,profile
from .routers import router

app_name = 'app_setup'
urlpatterns = [

    path('api/subcontractors/', subcontractor.list),
    path('api/subcontractors/<int:pk>/', subcontractor.detail),
    path('api/subcontractors/history/', subcontractor.history),
    path('api/subcontractors/extra/', subcontractor.extra),

    path('api/subcontractortypes/', subcontractortypes.list),
    path('api/subcontractortypes/<int:pk>/', subcontractortypes.detail),
    path('api/subcontractortypes/history/', subcontractortypes.history),

    path('api/units/', unit.list),
    path('api/units/<int:pk>/', unit.detail),
    path('api/units/history/', unit.history),

    path('api/paypurposes/', paypurpose.list),
    path('api/paypurposes/<int:pk>/', paypurpose.detail),
    path('api/paypurposes/history/', paypurpose.history),

    path('api/currencies/', currency.list),
    path('api/currencies/<int:pk>/', currency.detail),
    path('api/currencies/history/', currency.history),
    path('api/rate/<int:pk>/', currency.rate),
    path('api/currencies/default/', currency.default),
    path('api/convert/', currency.convert),

    path('api/accounts/', account.list),
    path('api/accounts/<int:pk>/', account.detail),
    path('api/accounts/history/', account.history),
    path('api/accounts/extra/', account.extra),

    path('api/legalforms/', legalform.list),
    path('api/legalforms/<int:pk>/', legalform.detail),
    path('api/legalforms/history/', legalform.history),

    path('api/taxetypes/', taxetype.list),
    path('api/taxetypes/<int:pk>/', taxetype.detail),
    path('api/taxetypes/history/', taxetype.history),

    path('api/projectcats/', projectcategory.list),
    path('api/projectcats/<int:pk>/', projectcategory.detail),
    path('api/projectcats/history/', projectcategory.history),

    path('api/projectsubcats/', projectsubcategory.list),
    path('api/projectsubcats/<int:pk>/', projectsubcategory.detail),
    path('api/projectsubcats/history/', projectsubcategory.history),
    path('api/projectsubcats/extra/', projectsubcategory.extra),

    path('api/brands/', brand.list),
    path('api/brands/<int:pk>/', brand.detail),
    path('api/brands/history/', brand.history),

    path('api/nbsources/', nbsource.list),
    path('api/nbsources/<int:pk>/', nbsource.detail),
    path('api/nbsources/history/', nbsource.history),

    path('api/nbformats/', nbformat.list),
    path('api/nbformats/<int:pk>/', nbformat.detail),
    path('api/nbformats/history/', nbformat.history),

    path('api/productcategories/', productcategory.list),
    path('api/productcategories/<int:pk>/', productcategory.detail),
    path('api/productcategories/history/', productcategory.history),

    path('api/projectproducts/', projectproduct.list),
    path('api/projectproducts/<int:pk>/', projectproduct.detail),
    path('api/projectproducts/history/', projectproduct.history),
    path('api/projectproducts/extra/', projectproduct.extra),

    path('api/team/', team.list),
    path('api/team/<int:pk>/', team.detail),
    path('api/team/extra/', team.extra),
    path('api/team/resend/<int:pk>/', team.user_resend),
    path('join/<subdomain>/<uidb64>/<token>/', team.join, name='join'),
    # path('users/create/', views.user_create, name='user_create'),
    # path('users/save/', views.user_save, name='user_save'),
    # path('users/update/<pk>', views.user_update, name='user_update'),
    # path('users/delete/<pk>', views.user_delete, name='user_delete'),

    path('api/profile/', profile.detail),
    path('api/profile/main/', profile.detail_main),


    #
    #
    # path('', views.index, name='index'),
    # path('docs_download/', views.docs_download, name='docs_download'),
    # path('users/', views.users_list, name='users'),
    # path('users/create/', views.user_create, name='user_create'),
    # path('users/save/', views.user_save, name='user_save'),
    # path('users/update/<pk>', views.user_update, name='user_update'),
    # path('users/delete/<pk>', views.user_delete, name='user_delete'),
    # path('join/<subdomain>/<uidb64>/<token>/', views.join, name='join'),
    # path('users/user_resend/<pk>', views.user_resend, name='user_resend'),
    #
    # path('profile/', views.profile, name='profile'),
    # path('profile/update', views.profile_update, name='profile_update'),
    #
    #
    #
    #
    #
    # path('units/', views.unit_list, name='units'),
    # path('units/create/', views.unit_create, name='unit_create'),
    # path('units/save/', views.unit_save, name='unit_save'),
    # path('units/update/<pk>', views.unit_update, name='unit_update'),
    # path('units/delete/<pk>', views.unit_delete, name='unit_delete'),
    # # path('units/history', views.unit_history, name='unit_history'),
    #
    # path('purposes/', views.purpose_list, name='purposes'),
    # path('purposes/create/', views.purpose_create, name='purpose_create'),
    # path('purposes/save/', views.purpose_save, name='purpose_save'),
    # path('purposes/update/<pk>', views.purpose_update, name='purpose_update'),
    # path('purposes/delete/<pk>', views.purpose_delete, name='purpose_delete'),
    # path('purposes/history', views.purpose_history, name='purpose_history'),
    #
    # path('currencies/', views.currency_list, name='currencies'),
    # path('currencies/create/', views.currency_create, name='currency_create'),
    # path('currencies/save/', views.currency_save, name='currency_save'),
    # path('currencies/update/<pk>', views.currency_update, name='currency_update'),
    # path('currencies/delete/<pk>', views.currency_delete, name='currency_delete'),
    # path('currencies/history', views.currency_history, name='currency_history'),
    # path('currencies/default', views.currency_default, name='currency_default'),
    # path('currencies/conversion', views.currency_conversion, name='currency_conversion'),
    #
    # path('rate/save/', views.rate_save, name='rate_save'),
    # path('rate/update/<pk>', views.rate_update, name='rate_update'),
    #
    # path('accounts/', views.account_list, name='accounts'),
    # path('accounts/create/', views.account_create, name='account_create'),
    # path('accounts/save/', views.account_save, name='account_save'),
    # path('accounts/update/<pk>', views.account_update, name='account_update'),
    # path('accounts/delete/<pk>', views.account_delete, name='account_delete'),
    # path('accounts/history', views.account_history, name='account_history'),
    #
    # path('legalforms/', views.legalform_list, name='legalforms'),
    # path('legalforms/create/', views.legalform_create, name='legalform_create'),
    # path('legalforms/save/', views.legalform_save, name='legalform_save'),
    # path('legalform/updates/<pk>', views.legalform_update, name='legalform_update'),
    # path('legalform/deletes/<pk>', views.legalform_delete, name='legalform_delete'),
    # path('legalforms/history', views.legalform_history, name='legalform_history'),
    #
    # path('taxetypes/', views.taxetype_list, name='taxetypes'),
    # path('taxetypes/create/', views.taxetype_create, name='taxetype_create'),
    # path('taxetypes/save/', views.taxetype_save, name='taxetype_save'),
    # path('taxetypes/updates/<pk>', views.taxetype_update, name='taxetype_update'),
    # path('taxetypes/deletes/<pk>', views.taxetype_delete, name='taxetype_delete'),
    # path('taxetypes/history', views.taxetype_history, name='taxetype_history'),
    #
    # path('subcontractortypes/', views.subcontractortype_list, name='subcontractortypes'),
    # path('subcontractortypes/create/', views.subcontractortype_create, name='subcontractortype_create'),
    # path('subcontractortypes/save/', views.subcontractortype_save, name='subcontractortype_save'),
    # path('subcontractortypes/updates/<pk>', views.subcontractortype_update, name='subcontractortype_update'),
    # path('subcontractortypes/deletes/<pk>', views.subcontractortype_delete, name='subcontractortype_delete'),
    # path('subcontractortypes/history', views.subcontractortype_history, name='subcontractortype_history'),
    #
    # path('nbsources/', views.nbsource_list, name='nbsources'),
    # path('nbsources/create/', views.nbsource_create, name='nbsource_create'),
    # path('nbsources/save/', views.nbsource_save, name='nbsource_save'),
    # path('nbsources/updates/<pk>', views.nbsource_update, name='nbsource_update'),
    # path('nbsources/deletes/<pk>', views.nbsource_delete, name='nbsource_delete'),
    # path('nbsources/history', views.nbsource_history, name='nbsource_history'),
    #
    # path('nbformats/', views.nbformat_list, name='nbformats'),
    # path('nbformats/create/', views.nbformat_create, name='nbformat_create'),
    # path('nbformats/save/', views.nbformat_save, name='nbformat_save'),
    # path('nbformats/updates/<pk>', views.nbformat_update, name='nbformat_update'),
    # path('nbformats/deletes/<pk>', views.nbformat_delete, name='nbformat_delete'),
    # path('nbformats/history', views.nbformat_history, name='nbformat_history'),
    #
    # path('productcategories/', views.productcategory_list, name='productcategories'),
    # path('productcategories/create/', views.productcategory_create, name='productcategory_create'),
    # path('productcategories/save/', views.productcategory_save, name='productcategory_save'),
    # path('productcategories/updates/<pk>', views.productcategory_update, name='productcategory_update'),
    # path('productcategories/deletes/<pk>', views.productcategory_delete, name='productcategory_delete'),
    # path('productcategories/history', views.productcategory_history, name='productcategory_history'),
    #
    # path('projectproducts/', views.projectproduct_list, name='projectproducts'),

backend/fins/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path('', include('app_about.urls')),
    # path('app/', include('app_frontend.urls')),
    path('app/', RedirectView.as_view(url='https://finsapp.ru'), name='app'),
    path('auth/', include('app_auth.urls')),
    path('signup/', include('app_signup.urls')),
    path('setup/', include('app_setup.urls')),
    path('dashboard/', include('app_dashboard.urls')),
    path('projects/', include('app_project.urls')),
    path('transactions/', include('app_transaction.urls')),
    path('docs/', include('app_docs.urls')),
    path('reports/', include('app_reports.urls')),
    path('admin/', admin.site.urls, name='admin'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # import debug_toolbar
    # urlpatterns = [
    #     path('__debug__/', include(debug_toolbar.urls)),
    #
    #     # For django versions before 2.0:
    #     # url(r'^__debug__/', include(debug_toolbar.urls)),
    #
    # ] + urlpatterns

backend/app_setup/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
# from app_signup.models import User
from fins.global_functions import IsDeletableMixin, BOOL_CHOICES_YESNO
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db import transaction
# from app_transaction.models import Unit as Ui
from app_signup import models as app_signup_models
from simple_history.models import HistoricalRecords
from django.conf import settings
import psycopg2


class Unit(models.Model, IsDeletableMixin):
    name = models.CharField(_('Юнит'), max_length=100, unique=True)

    is_deletable = models.BooleanField(_('Может быть удален'),default=True, choices = BOOL_CHOICES_YESNO)
    created_at = models.DateTimeField(_('Когда создан'), auto_now_add = True)
    # created_by = models.ForeignKey(DBUser, related_name='unit_created_by', on_delete=models.PROTECT, null=True)
    modified_at = models.DateTimeField(_('Когда изменен'), null=True, blank=True)
    # modified_by = models.ForeignKey(DBUser, related_name='unit_modified_by', on_delete=models.PROTECT, null=True)
    # history = HistoricalRecords(user_model=DBUser)

    class Meta:
        ordering = ['name']
        verbose_name = _('юнит')
        verbose_name_plural = _('юниты')

    def __str__(self):
        return self.name


class DBUser(models.Model):

    PERMISSION_TYPE_CHOICES = (
        (0, 'Доступ запрещен'),
        (1, 'Все проекты, где я участник'),
        (2, 'Все'),
        (3, 'Все проекты, где участник с моим юнитом'),
    )

    PERMISSION_TYPE_CHOICES2 = (
        (1, 'Все проекты, где участник'),
        (2, 'Все'),
        (3, 'Все проекты, где мой юнит и участник'),
    )

    PERMISSION_TYPE_CHOICES0 = (
        (2, 'Все'),
    )

    PERMISSION_TYPE_CHOICES3 = (
        (0, 'Да'),
        (1, 'Нет'),
    )

    user_id = models.SmallIntegerField()
    account_id = models.SmallIntegerField(blank=True, null=True)

    access_app_dashboard = models.PositiveSmallIntegerField(_('Доступ к Dashboard'), choices=PERMISSION_TYPE_CHOICES0, default=2)
    access_app_docs = models.PositiveSmallIntegerField(_('Доступ к Документам'), choices=PERMISSION_TYPE_CHOICES, default=1)
    access_app_setup = models.PositiveSmallIntegerField(_('Доступ к Настройкам'), choices=PERMISSION_TYPE_CHOICES3, default=1)
    access_app_project = models.PositiveSmallIntegerField(_('Доступ к Проектам и транзакциям'), choices=PERMISSION_TYPE_CHOICES, default=1)
    access_app_reports = models.PositiveSmallIntegerField(_('Доступ к Отчетам'), choices=PERMISSION_TYPE_CHOICES, default=1)
    access_users = models.PositiveSmallIntegerField(_('Доступ к Пользователям'), choices=PERMISSION_TYPE_CHOICES3, default=1)
    access_can_block = models.PositiveSmallIntegerField(_('Может блокировать редактирование и скрывать'), choices=PERMISSION_TYPE_CHOICES3, default=1)

    is_active = models.BooleanField(_('Активен'), choices = BOOL_CHOICES_YESNO, default=True)
    is_owner = models.BooleanField(_('Владелец'), choices = BOOL_CHOICES_YESNO, default=False)

    unit = models.ForeignKey(Unit, verbose_name = 'Юнит', on_delete=models.PROTECT, blank=True, null=True)

    invited_at = models.DateTimeField(_('Когда приглашен'), null=True)
    invited_by = models.SmallIntegerField(_('Кто пригласил'), null=True)
    joined_at = models.DateTimeField(_('Когда присоединился'), null=True)
    is_joined = models.BooleanField(_('Присоединился'), default=False, choices = BOOL_CHOICES_YESNO)


    def __str__(self):
        # return ''
        return str(app_signup_models.User.objects.get(pk=self.user_id).get_full_name())
    def get_name(self):
        return str(app_signup_models.User.objects.get(pk=self.user_id).get_full_name())

    @receiver(post_save, sender=app_signup_models.User)
    def create_user_profile(sender, instance, created, using, **kwargs):
        if created:
            try:
                with transaction.atomic():
                    DBUser.objects.create(
                        user_id=instance.pk
                    )
            except Exception:
                if instance.is_superuser:
                    pass
                else:
                    db = 'account_' + str(instance.created_account_pk)
                    with transaction.atomic():
                        DBUser.objects.using(db).create(
                            user_id=instance.pk,
                            account_id=instance.created_account_pk
                        )



    def get_main_user(self):
        return app_signup_models.Account.objects.get(pk=self.account_id).users.all().get(pk=self.user_id)


    @property
    def email(self):
        return self.get_main_user().email
    @property
    def first_name(self):
        return self.get_main_user().first_name
    @property
    def last_name(self):
        return self.get_main_user().last_name
    @property
    def invited_by_full(self):
        return app_signup_models.Account.objects.get(pk=self.account_id).users.all().get(pk=self.invited_by).get_full_name()


    # @receiver(post_save, sender=app_signup_models.User)
    # def save_user_profile(sender, instance, **kwargs):
    #     instance.dbuser.save()

backend/app_setup/templates/app_setup/users/account_activation_invalid.html
Ошибка

backend/app_setup/templates/app_setup/users/partial_user_create.html
{% load widget_tweaks %}


<form method="post" action="{% url 'app_setup:user_create' %}" class="js-user-create-form"
onsubmit="addspinner(this)"
id="userInviteForm"
>
    {% csrf_token %}

    <div class="modal-header">
            <h4 >
                Добавление контрагента
            </h4>
            <button type="button" class="close " data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true"><i class="far fa-times close-icon"></i></span>
            </button>
    </div>

    <div class="modal-body">
        {% include 'app_setup/users/partial_user_form.html' %}
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-outline-danger btn-lg pl-5 pr-5" data-dismiss="modal">Отмена</button>
        <button type="submit" class="btn btn-success btn-lg pl-5 pr-5">Создать</button>
    </div>


</form>

backend/app_setup/templates/app_setup/users/partial_user_delete.html
<form method="post" action="{% url 'app_setup:user_delete' usr.pk %}" class="js-user-delete-form"
onsubmit="addspinner(this)"
id="userInviteForm"
>
  {% csrf_token %}

<div class="modal-header">
        <h4 >
            Удаление пользователя
        </h4>
        <button type="button" class="close " data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"><i class="far fa-times close-icon"></i></span>
        </button>
</div>

          <div class="modal-body">
            <p class="lead">Вы уверены, что хотите удалить пользоватлея <strong>{{ usr.user_id }}</strong>?</p>
          </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-outline-danger btn-lg pl-5 pr-5" data-dismiss="modal">Отмена</button>
            <button type="submit" class="btn btn-success btn-lg pl-5 pr-5">Удалить</button>
        </div>


</form>

backend/app_setup/templates/app_setup/users/partial_user_form.html
{% load widget_tweaks %}
{% if messages %}
    {% for message in messages %}
        <p>{{ message }}</p>
    {% endfor %}
{% endif %}

{{ form_user.as_p }}

backend/app_setup/templates/app_setup/users/partial_user_update.html
{% load widget_tweaks %}

<form method="post" action="{% url 'app_setup:user_update' form_user.instance.pk %}" class="js-user-update-form"
onsubmit="addspinner(this)"
id="userInviteForm"
>
{% csrf_token %}


<div class="modal-header">
        <h4 >
            Редактирование прав доступа
        </h4>
        <button type="button" class="close " data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"><i class="far fa-times close-icon"></i></span>
        </button>
</div>

<div class="modal-body">
    {% include 'app_setup/users/partial_user_form.html' %}
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-outline-danger btn-lg pl-5 pr-5" data-dismiss="modal">Отмена</button>
    <button type="submit" class="btn btn-success btn-lg pl-5 pr-5">Сохранить</button>
</div>


</form>

backend/app_setup/templates/app_setup/users/partial_users_list.html
{% for user in users_list %}

    <div class="row mt-3 mb-3  mr-1 px-4 py-4 border border-1">
        <div class="col-4 d-flex flex-column justify-content-between">
            <div class="d-flex justify-content-between">

                <div>
                    <h5 style="white-space: nowrap">{{ user.first_name }} {{ user.last_name }}
                        <br>
                        {% if user.is_joined %}
                            <span class="badge badge-success">
                                <span>Подключен </span>
                            </span>
                        {% else %}
                            <form method="post"   id="sendagain" action="{% url 'app_setup:user_resend' user.id %}">
                                {% csrf_token %}
                                <span class="badge badge-warning">
                                    <span>Не подключен </span>
                                </span>
                                <button type="submit" class="js-resend-user btn btn-link btn-sm" >Выслать повторно</button>
                            </form>
                        {% endif%}
                    </h5>
                </div>
                <div >
                    <small class="d-flex flex-column align-items-end">
                        <span class=" font-weight-lighter">{{ user.email }}</span>
                         <span class="font-weight-lighter">{{ user.unit| default_if_none:wording.none_unit }}</span>
                    </small>
                </div>
            </div>
            <div class="d-flex justify-content-between">
                <small class="font-weight-lighter text-black-50 ">Приглашен {{ user.invited_at.date }}</small>

                <button type="button"
                    class="js-delete-user btn btn-sm btn-outline-secondary border-0 align-self-start"
                    data-url="{% url 'app_setup:user_delete' user.id %}">
                     <i class="fas fa-trash mr-2"></i> Удалить из компании
                </button>
            </div>
        </div>





        <div class="col-4">
            <h5>Права
                <button type="button"
                    class="js-update-user btn btn-sm btn-link"
                      data-url="{% url 'app_setup:user_update' user.id %}">
                    Изменить<i class="far fa-pencil ml-2"></i>
                </button>
            </h5>
            <small style="line-height: 2;">

                <table class=" w-100">
                    <tr>
                        <td style="width:230px;">Раздел Dashboard</td>
                        <td class="text-right font-weight-bold">{{ user.get_access_app_dashboard_display }}</td>
                    </tr>
                    <tr>
                        <td>Раздел Документы</td>
                        <td class="text-right font-weight-bold">{{ user.get_access_app_docs_display }}</td>
                    </tr>
                    <tr>
                        <td>Раздел Настройки</td>
                        <td class="text-right font-weight-bold">{{ user.get_access_app_setup_display }}</td>
                    </tr>
                    <tr>
                        <td>Раздел Проекты и транзакции</td>
                        <td class="text-right font-weight-bold">{{ user.get_access_app_project_display }}</td>
                    </tr>

                </table>
            </small>

        </div>
        <div class="col-4 " >

            <small style="line-height: 2;">
                <table class="w-100" style="margin-top: 40px !important;">
                    <tr>
                        <td>Раздел Отчеты</td>
                        <td class="text-right font-weight-bold">{{ user.get_access_app_reports_display }}</td>
                    </tr>
                    <tr>
                        <td>Раздел Пользователи</td>
                        <td class="text-right font-weight-bold">{{ user.get_access_users_display }}</td>
                    </tr>
                    <tr>
                        <td>Может блокировать проекты</td>
                        <td class="text-right font-weight-bold">{{ user.get_access_can_block_display }}</td>
                    </tr>
                </table>
            </small>
        </div>
        <hr/>
    </div>

{% endfor %}

backend/app_setup/templates/app_setup/users/user_in_db_invite_email.html
{% autoescape off %}
Hi

Please click on the link below to confirm your registration:
{{link}}

{% endautoescape %}

backend/app_setup/templates/app_setup/users/user_invite_email.html
{% autoescape off %}
Hi
{{user.firstname}}
Please click on the link below to confirm your registration:
http://{{ domain }}{% url 'app_setup:join' uidb64=uid token=token subdomain=subdomain %}

{% endautoescape %}

backend/app_setup/templates/app_setup/users/user_join_password.html
<form method="post">
    {% csrf_token %}
    {{ pass_form.as_p }}
    <button type="submit">Продолжить</button>
  </form>

backend/app_setup/templates/app_setup/users/users.html
{% extends 'base_app.html' %}
{% load static %}

{% block header %}
    <div style="white-space: nowrap;">
        <h1 class="title">
            Команда
        </h1>
    </div>
    <div>
        <button  type="submit" class="js-create-user btn btn-primary btn pr-3 pl-3 pt-2 pb-2 ml-5" data-url="{% url 'app_setup:user_create' %}">
            Добавить в команду
        </button>
    </div>

{% endblock %}


{% block content %}

<div class="block-section-3 mb-5" id="users_list">
    <div id="resend_message"></div>

    {% include 'app_setup/users/partial_users_list.html' %}

</div>

<div class="modal fade" id="modal-user">
    <div class="modal-dialog">
          <div class="modal-content">
         </div>
    </div>
</div>

{% endblock %}


{% block javascript %}
    <script type='text/javascript' src="{% static 'js/users.js' %}"></script>
{% endblock %}