backend/app_about/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'app_about'
urlpatterns = [
    path('', views.index, name='index'),
    path('en/', views.index_en, name='index_en'),



]

backend/app_signup/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'app_signup'
urlpatterns = [
    path('', views.signup, name='signup'),
    path('en/', views.signup_en, name='signup_en'),
    path('modal-help/', views.modal_help, name='modal_help'),



]

backend/fins/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path('', include('app_about.urls')),
    # path('app/', include('app_frontend.urls')),
    path('app/', RedirectView.as_view(url='https://finsapp.ru'), name='app'),
    path('auth/', include('app_auth.urls')),
    path('signup/', include('app_signup.urls')),
    path('setup/', include('app_setup.urls')),
    path('dashboard/', include('app_dashboard.urls')),
    path('projects/', include('app_project.urls')),
    path('transactions/', include('app_transaction.urls')),
    path('docs/', include('app_docs.urls')),
    path('reports/', include('app_reports.urls')),
    path('admin/', admin.site.urls, name='admin'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # import debug_toolbar
    # urlpatterns = [
    #     path('__debug__/', include(debug_toolbar.urls)),
    #
    #     # For django versions before 2.0:
    #     # url(r'^__debug__/', include(debug_toolbar.urls)),
    #
    # ] + urlpatterns

backend/app_signup/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm, Textarea
from .models import *
from django.utils.translation import gettext_lazy as _
from app_signup import models as app_signup_models

class SignUpForm(UserCreationForm):


    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )


class JoinSignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            'password1',
            'password2',
        )

class AccountCreationForm(ModelForm):


    error_messages = {
            'duplicate_subdomain': _("Субдомен уже занят"),
    }

    class Meta:
        model = Account
        fields = (
            'name',
            'subdomain',
        )

        labels = {
            'name': _('Название компании'),
            'subdomain': _('Субдомен компании'),
        }
        help_texts = {
            'name': _('Укажите название компании'),
            'subdomain': _('Укажите субдомен для отображения колмпании'),
        }


    def clean_subdomain(self):
        subdomain = self.cleaned_data["subdomain"]

        try:
            Account._default_manager.get(subdomain=subdomain)
            raise forms.ValidationError(
                self.error_messages['duplicate_subdomain'],
                code='duplicate_subdomain',
            )
        except Account.DoesNotExist:
            return subdomain


class WordingTextForm(ModelForm):
    text = forms.CharField( widget=forms.Textarea )



    class Meta:
        model = app_signup_models.Wording
        fields = ('__all__')



class SignUpFormEng(UserCreationForm):


    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )
        labels = {
            'first_name': _('First name'),
            'last_name': _('Last name'),
            'email': _('Email'),
            'password1': _('Password'),
            'password2': _('Repeat your password '),
        }


class AccountCreationFormEng(ModelForm):


    error_messages = {
            'duplicate_subdomain': _("Субдомен уже занят"),
    }

    class Meta:
        model = Account
        fields = (
            'name',
            'subdomain',
        )

        labels = {
            'name': _('Company name'),
            'subdomain': _('Choose your subdomain'),
        }
        help_texts = {
            'name': _('Укажите название компании'),
            'subdomain': _('Укажите субдомен для отображения колмпании'),
        }


    def clean_subdomain(self):
        subdomain = self.cleaned_data["subdomain"]

        try:
            Account._default_manager.get(subdomain=subdomain)
            raise forms.ValidationError(
                self.error_messages['duplicate_subdomain'],
                code='duplicate_subdomain',
            )
        except Account.DoesNotExist:
            return subdomain

backend/app_signup/views.py
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect
from subdomains.utils import reverse as sub_reverse
from .forms import *
from datetime import datetime
import pytz
from django.contrib import messages
import logging
from .models import *
from app_setup import models as app_setup_models
from django.contrib.auth.decorators import login_required
from app_auth.decorators import access_company_level
from django.http import JsonResponse
from django.template.loader import render_to_string
from app_signup.tools import access_default
from django.contrib.sites.shortcuts import get_current_site
from django.db import transaction


logger = logging.getLogger(__name__)



def signup(request):


    if request.method == 'POST':
        user_form = SignUpForm(request.POST)
        account_form = AccountCreationForm(request.POST)

        if account_form.is_valid() and user_form.is_valid():
            account_instance = account_form.save()
            account_instance.create_database()
            account_instance.fill_database()

            noerror = True
            if len(User.objects.filter(email=user_form.data['email'])) != 0:
                instance = User.objects.get(email=user_form.data['email'])
                instance.created_account_pk = account_instance.pk
                # email = instance.email
                # raw_password = instance.password
                try:
                    with transaction.atomic():
                        app_setup_models.DBUser.objects.create(user_id=instance.pk)
                except Exception:
                    if instance.is_superuser:
                        pass
                    else:
                        db = 'account_' + str(instance.created_account_pk)
                        with transaction.atomic():
                            app_setup_models.DBUser.objects.using(db).create(user_id=instance.pk)

            else:
                if user_form.is_valid():
                    instance = user_form.save(commit=False)
                    instance.created_account_pk = account_instance.pk
                    # email = user_form.cleaned_data.get('email')
                    # raw_password = user_form.cleaned_data.get('password1')
                else:
                    noerror = False

            if noerror:

                instance.save()
                instance.account.add(account_instance)
                dbuser = app_setup_models.DBUser.objects.using('account_' + str(account_instance.pk)).get(user_id=instance.id)
                dbuser.is_owner = True
                dbuser.is_joined = True
                dbuser.joined_at = pytz.utc.localize(datetime.utcnow())
                access_default(dbuser)
                dbuser.save(using=('account_' + str(account_instance.pk)))

                owner_info = app_signup_models.Owner(user= instance,account=account_instance)
                owner_info.save()


                # user = authenticate(username=email, password=raw_password)
                # login(request, user)
                login(request, instance)

                subject = 'Добро пожаловать в FinS'
                message = render_to_string('app_signup/emails/welcome_email.html', {
                    'user': instance,
                    'domain': get_current_site(request).domain,
                })
                instance.email_user(subject, message)
                email_info = app_signup_models.Emails(account=account_instance, welcome_is_sent=True, welcome_date = pytz.utc.localize(datetime.utcnow()))
                email_info.save()

                return redirect(sub_reverse(settings.LOGIN_REDIRECT_URL, subdomain=account_instance.subdomain, scheme='https'))
            else:
                messages.error(request, 'Ошибка валидации формы')
        else:
            messages.error(request, 'Ошибка валидации формы')
    else:
        if request.user.is_authenticated:
            logout(request)
        user_form = SignUpForm()
        account_form = AccountCreationForm()

    return render(request, 'app_signup/signup.html',
                {
                'user_form': user_form,
                'account_form': account_form,
                })



@login_required
@access_company_level
def modal_help(request):
    data = {}
    raw_code = request.GET.get('code')
    if raw_code:
        code = raw_code.split('_')[1]
        text = app_signup_models.Wording.objects.get(code=code).text
    else:
        text = 'Ошибка'
    context = {'text': text,}
    template = 'app_signup/help_modal.html'
    data['html'] = render_to_string(template, context)
    return JsonResponse(data)



def signup_en(request):


    if request.method == 'POST':
        user_form = SignUpFormEng(request.POST)
        account_form = AccountCreationFormEng(request.POST)
        if account_form.is_valid():
            account_instance = account_form.save()
            account_instance.create_database()
            account_instance.fill_database()

            noerror = True
            if len(User.objects.filter(email=user_form.data['email'])) != 0:
                instance = User.objects.get(email=user_form.data['email'])
                instance.created_account_pk = account_instance.pk
                # email = instance.email
                # raw_password = instance.password
                try:
                    with transaction.atomic():
                        app_setup_models.DBUser.objects.create(user_id=instance.pk)
                except Exception:
                    if instance.is_superuser:
                        pass
                    else:
                        db = 'account_' + str(instance.created_account_pk)
                        with transaction.atomic():
                            app_setup_models.DBUser.objects.using(db).create(user_id=instance.pk)

            else:
                if user_form.is_valid():
                    instance = user_form.save(commit=False)
                    instance.created_account_pk = account_instance.pk
                    # email = user_form.cleaned_data.get('email')
                    # raw_password = user_form.cleaned_data.get('password1')
                else:
                    noerror = False

            if noerror:

                instance.save()
                instance.account.add(account_instance)
                dbuser = app_setup_models.DBUser.objects.using('account_' + str(account_instance.pk)).get(user_id=instance.id)
                dbuser.is_owner = True
                dbuser.is_joined = True
                dbuser.joined_at = pytz.utc.localize(datetime.utcnow())
                access_default(dbuser)
                dbuser.save(using=('account_' + str(account_instance.pk)))

                owner_info = app_signup_models.Owner(user= instance,account=account_instance)
                owner_info.save()


                # user = authenticate(username=email, password=raw_password)
                # login(request, user)
                login(request, instance)

                subject = 'Добро пожаловать в FinS'
                message = render_to_string('app_signup/emails/welcome_email.html', {
                    'user': instance,
                    'domain': get_current_site(request).domain,
                })
                instance.email_user(subject, message)
                email_info = app_signup_models.Emails(account=account_instance, welcome_is_sent=True, welcome_date = pytz.utc.localize(datetime.utcnow()))
                email_info.save()

                return redirect(sub_reverse(settings.LOGIN_REDIRECT_URL, subdomain=account_instance.subdomain, scheme='https'))
            else:
                messages.error(request, 'Ошибка валидации формы')
        else:
            messages.error(request, 'Ошибка валидации формы')
    else:
        if request.user.is_authenticated:
            logout(request)
        user_form = SignUpFormEng()
        account_form = AccountCreationFormEng()

    return render(request, 'app_signup/signup_en.html',
                {
                'user_form': user_form,
                'account_form': account_form,
                })

backend/app_signup/templates/app_signup/help_modal.html
{% load widget_tweaks %}




    <div class="modal-header">
            <h4 >
                Подсказка
            </h4>
            <button type="button" class="close " data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true"><i class="far fa-times-circle close-icon"></i></span>
            </button>
    </div>

    <div class="modal-body-3">
        {{text}}
    </div>

    <div class="modal-footer">
        <button type="button" class="button-outline" data-dismiss="modal">Понял</button>
    </div>

backend/app_signup/templates/app_signup/signup.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="google" value="notranslate"/>
        <title>FinS | Financial CRM</title>
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome-all.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/style_signup.css' %}" />
        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type=image/x-icon>
        <script src="https://cdn.jsdelivr.net/npm/vue@2.6.12"></script>
    </head>

    <body>
        <div class="container">
            <a href="{% url 'app_about:index' %}"><img width='140' class="mt-4" src="{% static 'img/finslogo.svg' %}"></a>

            <h2 style="margin-top: 70px; margin-bottom: 50px;">Присоединиться к FinS</h2>
            <div class="row " style="margin-bottom: 100px;" id="app">
                <div class="col-12 ">
                    {% if messages %}
                        <div class="alert alert-danger" role="alert">
                            {% for message in messages %}
                                <span>{{ message }}</span>
                            {% endfor %}
                        </div>
                    {% endif %}
                    <form method="post">
                        {% csrf_token %}

                        {{ user_form.non_field_errors }}

                        {% for hidden_field in user_form.hidden_fields %}
                        {{ hidden_field.errors }}
                        {{ hidden_field }}
                        {% endfor %}

                        {% for field in user_form.visible_fields %}
                        {{ field.label_tag}}
                        {% render_field field  class="form-control mb-3" %}
                        {{ field.errors}}
                        {% endfor %}


                        {{ account_form.non_field_errors }}

                        {% for hidden_field in account_form.hidden_fields %}
                        {{ hidden_field.errors }}
                        {{ hidden_field }}
                        {% endfor %}

                        {% for field in account_form.visible_fields %}
                        {{ field.label_tag }}
                        {% render_field field  class="form-control mb-3" %}
                        {{ field.errors }}
                        {% endfor %}

                        <button class="btn btn-lg mt-5 btn-primary btn-block" :disabled="isDisabled" type="submit" id="signup" v-on:click="onClick">
                            <span v-if="!isDisabled">Зарегистрироваться</span>
                            <div v-else style="display: flex;justify-content: center;">
                                <div class="spinner-grow text-light" role="status">
                                    <span class="sr-only">Loading...</span>
                                </div>
                                Создаем аккаунт
                            </div>
                        </button>

                    </form>
                </div>
            </div>
        </div>
        <script>
            var app = new Vue({
              el: '#app',
              data: {
                isDisabled: false,
              },
                methods:{
                  onClick(){
                      // console.log('cliccccc')
                      //  this.isDisabled = true
                      setTimeout(()=>{
                          this.isDisabled = true
                      }, 500)

                  },
                },
            })
        </script>
    </body>
</html>

backend/app_signup/templates/app_signup/signup_en.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="google" value="notranslate"/>
        <title>FinS | Sign up</title>
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-4.4.1/dist/css/bootstrap.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome-all.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/style_signup.css' %}" />
        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type=image/x-icon>
    </head>

    <body>
        <div class="container">
            <a href="{% url 'app_about:index' %}"><img width='140' class="mt-4" src="{% static 'img/finslogo.svg' %}"></a>

            <h2 style="margin-top: 70px; margin-bottom: 50px;">Join FinS</h2>
            <div class="row " style="margin-bottom: 100px;">
                <div class="col-12 ">
                    {% if messages %}
                        <div class="alert alert-danger" role="alert">
                            {% for message in messages %}
                                <span>{{ message }}</span>
                            {% endfor %}
                        </div>
                    {% endif %}
                    <form method="post" onsubmit="addspinner(this,'signup')">
                        {% csrf_token %}

                        {{ user_form.non_field_errors }}

                        {% for hidden_field in user_form.hidden_fields %}
                        {{ hidden_field.errors }}
                        {{ hidden_field }}
                        {% endfor %}

                        {% for field in user_form.visible_fields %}
                        {{ field.label_tag}}
                        {% render_field field  class="form-control mb-3" %}
                        {{ field.errors}}
                        {% endfor %}


                        {{ account_form.non_field_errors }}

                        {% for hidden_field in account_form.hidden_fields %}
                        {{ hidden_field.errors }}
                        {{ hidden_field }}
                        {% endfor %}

                        {% for field in account_form.visible_fields %}
                        {{ field.label_tag }}
                        {% render_field field  class="form-control mb-3" %}
                        {{ field.errors }}
                        {% endfor %}

                        <button class="btn btn-lg mt-5 btn-primary btn-block" type="submit" id="signup">Sign up</button>

                    </form>
                </div>
            </div>
        </div>
    </body>
</html>