backend/app_about/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'app_about'
urlpatterns = [
    path('', views.index, name='index'),
    path('en/', views.index_en, name='index_en'),



]

backend/app_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'app_project'
urlpatterns = [
    # path('', views.index, name='index'),
    # path('project/<pk>/', views.project, name='project'),
    path('api/', views.project_list),
    path('api/<int:pk>/', views.project_detail),
    path('api/extra/', views.project_extra),
    path('api/statistics/<int:pk>/', views.project_statistics),
    path('api/history/', views.project_history),
    path('api/excel/', views.excel_export),

    path('api/team_list/<int:pk>/', views.project_team_list),
    path('api/team/<int:pk>/', views.project_team_detail),

    path('api/service_list/<int:pk>/', views.project_service_list),
    path('api/service/<int:pk>/', views.project_service_detail),

    path('api/period_list/<int:pk>/', views.project_period_list),
    path('api/period/<int:pk>/', views.project_period_detail),

    path('api/report_list/<int:pk>/', views.project_report_list),
    path('api/report/<int:pk>/', views.project_report_detail),





    # path('project/<pk>/', views.project, name='project'),
    # path('project_create/', views.project_create, name='project_create'),
    # path('project_update/<pk>/', views.project_update, name='project_update'),
    # path('project_update_estimation/<pk>/', views.project_update_estimation, name='project_update_estimation'),
    # path('project_delete/<pk>/', views.project_delete, name='project_delete'),
    #
    # path('project/history', views.project_history, name='project_history'),
    #
    # path('ajax/load-subcat/', views.load_subcat, name='ajax_load_subcat'),
    #
    # path('create_period/<projectpk>/', views.create_period, name='create_period'),
    # path('update_period/<pk>/', views.update_period, name='update_period'),
    # path('delete_period/<pk>/', views.delete_period, name='delete_period'),
    #
    # path('service_create/<projectpk>/', views.service_create, name='service_create'),
    # path('service_update/<pk>/', views.service_update, name='service_update'),
    # path('service_delete/<pk>/', views.service_delete, name='service_delete'),
    #
    # path('report_create/<projectpk>/<periodpk>', views.report_create, name='report_create'),
    # path('report_update/<pk>/<projectpk>', views.report_update, name='report_update'),
    # path('report_delete/<pk>/', views.report_delete, name='report_delete'),
    #
    # path('team_create/<projectpk>/', views.team_create, name='team_create'),
    # path('team_update/<pk>/', views.team_update, name='team_update'),
    # path('team_delete/<pk>/', views.team_delete, name='team_delete'),
    #
    # path('excel_export/', views.excel_export, name='excel_export'),

]

backend/fins/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path('', include('app_about.urls')),
    # path('app/', include('app_frontend.urls')),
    path('app/', RedirectView.as_view(url='https://finsapp.ru'), name='app'),
    path('auth/', include('app_auth.urls')),
    path('signup/', include('app_signup.urls')),
    path('setup/', include('app_setup.urls')),
    path('dashboard/', include('app_dashboard.urls')),
    path('projects/', include('app_project.urls')),
    path('transactions/', include('app_transaction.urls')),
    path('docs/', include('app_docs.urls')),
    path('reports/', include('app_reports.urls')),
    path('admin/', admin.site.urls, name='admin'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # import debug_toolbar
    # urlpatterns = [
    #     path('__debug__/', include(debug_toolbar.urls)),
    #
    #     # For django versions before 2.0:
    #     # url(r'^__debug__/', include(debug_toolbar.urls)),
    #
    # ] + urlpatterns

backend/app_project/views/excel.py
from app_project.decorators import *
from app_auth.decorators import access_company_level
from django.contrib.auth.decorators import login_required
from app_project import models as app_project_models
from app_project.tools import filter_extra_data
from app_project.filters import ProjectsFilter
from django.http import HttpResponse
import xlwt
import datetime
from django.contrib.sites.models import Site


@login_required
@access_company_level
@access_app_projects_list
def excel_export(request, get_access_all):
    project_filter_qs = request.session['project_filter_qs']
    queryset = get_access_all().filter(pk__in=project_filter_qs)

    filter = ProjectsFilter(request.GET, queryset=queryset)
    filter = filter_extra_data(filter)

    response = HttpResponse(content_type='application/ms-excel')
    filename = str(Site.objects.all()[0]) + '_projects_' + str(datetime.datetime.now())
    response['Content-Disposition'] = 'attachment; filename=' + filename + '.xls'
    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet("Проекты")

    #table header
    row_num = 0
    model = app_project_models.Project
    columns = [
        (str(model._meta.get_field('name').verbose_name), 4000),
        (str(model._meta.get_field('name_short').verbose_name), 4000),
        (str(model._meta.get_field('brand').verbose_name), 4000),
        (str(model._meta.get_field('category').verbose_name), 4000),
        (str(model._meta.get_field('subcategory').verbose_name), 4000),
        (str(model._meta.get_field('work_format').verbose_name), 4000),
        (str(model._meta.get_field('agreement_format').verbose_name), 4000),
        (str(model._meta.get_field('commission').verbose_name), 4000),
        (str(model._meta.get_field('stage').verbose_name), 4000),
        (str(model._meta.get_field('project_start').verbose_name), 4000),
        (str(model._meta.get_field('project_end').verbose_name), 4000),
        ("Лидер проекта", 4000),
        ("Команда проекта", 4000),
        ("Юниты", 4000),
        ("Выручка проекта (в основной валюте)", 4000),
        ("Внешние расходы проекта (в основной валюте)", 4000),
        ("Валовая прибыль проекта (в основной валюте)", 4000),
        ("РВП проекта (в основной валюте)", 4000),

        (str(model._meta.get_field('nb_source').verbose_name), 4000),
        (str(model._meta.get_field('nb_format').verbose_name), 4000),
        (str(model._meta.get_field('estimate_probability').verbose_name), 4000),
        (str(model._meta.get_field('estimate_presale_start').verbose_name), 4000),
        (str(model._meta.get_field('estimate_presale_end').verbose_name), 4000),
        (str(model._meta.get_field('estimate_presale_outcome_ext').verbose_name), 4000),
        (str(model._meta.get_field('estimate_presale_outcome_int').verbose_name), 4000),
        (str(model._meta.get_field('estimate_inprogress_start').verbose_name), 4000),
        (str(model._meta.get_field('estimate_inprogress_end').verbose_name), 4000),
        (str(model._meta.get_field('estimate_inprogress_income_before_taxes').verbose_name), 4000),
        (str(model._meta.get_field('estimate_inprogress_gross_profitability_before_taxes').verbose_name), 4000),
        (str(model._meta.get_field('estimate_inprogress_gross_profit_before_taxes').verbose_name), 4000),
        (str(model._meta.get_field('estimate_inprogress_project_profitability_before_taxes').verbose_name), 4000),
        (str(model._meta.get_field('estimate_inprogress_project_profit_before_taxes').verbose_name), 4000),



        (str(model._meta.get_field('created_at').verbose_name), 4000),
        (str(model._meta.get_field('created_by').verbose_name), 4000),
        (str(model._meta.get_field('modified_at').verbose_name), 4000),
        (str(model._meta.get_field('modified_by').verbose_name), 4000),



    ]
    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    #rows
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num][0], font_style)
        # set column width
        ws.col(col_num).width = columns[col_num][1]

    font_style = xlwt.XFStyle()
    font_style.alignment.wrap = 1



    for obj in filter.qs:


        if obj.category == None:
            category = ''
        else:
            category = obj.category.name

        if obj.subcategory == None:
            subcategory = ''
        else:
            subcategory = obj.subcategory.name


        if obj.work_format == None:
            work_format = ''
        else:
            work_format = obj.get_work_format_display()

        if obj.agreement_format == None:
            agreement_format = ''
        else:
            agreement_format = obj.get_agreement_format_display()

        if obj.stage == None:
            stage = ''
        else:
            stage = obj.get_stage_display()

        if obj.brand == None:
            brand = ''
        else:
            brand = obj.brand.name

        if obj.project_start == None:
            project_start = ''
        else:
            project_start = obj.project_start.strftime("%d/%m/%Y")

        if obj.project_end == None:
            project_end = ''
        else:
            project_end = obj.project_end.strftime("%d/%m/%Y")


        if obj.leader == None:
            leader = ''
        else:
            leader = str(obj.leader)

        if obj.team == None:
            team = ''
        else:
            team = str(obj.team)

        if obj.units == None:
            units = ''
        else:
            units = str(obj.units)



        if obj.nb_source == None:
            nb_source = ''
        else:
            nb_source = obj.nb_source.name

        if obj.nb_format == None:
            nb_format = ''
        else:
            nb_format = obj.nb_format.name

        if obj.estimate_probability == None:
            estimate_probability = ''
        else:
            estimate_probability = obj.estimate_probability

        if obj.estimate_presale_start == None:
            estimate_presale_start = ''
        else:
            estimate_presale_start = obj.estimate_presale_start.strftime("%d/%m/%Y")

        if obj.estimate_presale_end == None:
            estimate_presale_end = ''
        else:
            estimate_presale_end = obj.estimate_presale_end.strftime("%d/%m/%Y")

        if obj.estimate_presale_outcome_ext == None:
            estimate_presale_outcome_ext = ''
        else:
            estimate_presale_outcome_ext = obj.estimate_presale_outcome_ext

        if obj.estimate_presale_outcome_int == None:
            estimate_presale_outcome_int = ''
        else:
            estimate_presale_outcome_int = obj.estimate_presale_outcome_int

        if obj.estimate_inprogress_start == None:
            estimate_inprogress_start = ''
        else:
            estimate_inprogress_start = obj.estimate_inprogress_start.strftime("%d/%m/%Y")

        if obj.estimate_inprogress_end == None:
            estimate_inprogress_end = ''
        else:
            estimate_inprogress_end = obj.estimate_inprogress_end.strftime("%d/%m/%Y")

        if obj.estimate_inprogress_income_before_taxes == None:
            estimate_inprogress_income_before_taxes = ''
        else:
            estimate_inprogress_income_before_taxes = obj.estimate_inprogress_income_before_taxes

        if obj.estimate_inprogress_gross_profitability_before_taxes == None:
            estimate_inprogress_gross_profitability_before_taxes = ''
        else:
            estimate_inprogress_gross_profitability_before_taxes = obj.estimate_inprogress_gross_profitability_before_taxes

        if obj.estimate_inprogress_gross_profit_before_taxes == None:
            estimate_inprogress_gross_profit_before_taxes = ''
        else:
            estimate_inprogress_gross_profit_before_taxes = obj.estimate_inprogress_gross_profit_before_taxes

        if obj.estimate_inprogress_project_profitability_before_taxes == None:
            estimate_inprogress_project_profitability_before_taxes = ''
        else:
            estimate_inprogress_project_profitability_before_taxes = obj.estimate_inprogress_project_profitability_before_taxes

        if obj.estimate_inprogress_project_profit_before_taxes == None:
            estimate_inprogress_project_profit_before_taxes = ''
        else:
            estimate_inprogress_project_profit_before_taxes = obj.estimate_inprogress_project_profit_before_taxes


        if obj.created_at == None:
            created_at = ''
        else:
            created_at = obj.created_at.replace(tzinfo=None).strftime("%d/%m/%Y")

        if obj.created_by == None:
            created_by = ''
        else:
            created_by = str(obj.created_by)

        if obj.modified_at == None:
            modified_at = ''
        else:
            modified_at = obj.modified_at.replace(tzinfo=None).strftime("%d/%m/%Y")

        if obj.modified_by == None:
            modified_by = ''
        else:
            modified_by = str(obj.modified_by)









        row_num += 1
        row = [
            obj.name,
            obj.name_short,
            brand,
            category,
            subcategory,
            work_format,
            agreement_format,
            obj.commission,
            stage,
            project_start,
            project_end,
            leader,
            team,
            units,
            obj.income,
            obj.outcome_ext,
            obj.gross_profit,
            obj.gross_profitability,




            nb_source,
            nb_format,
            estimate_probability,
            estimate_presale_start,
            estimate_presale_end,
            estimate_presale_outcome_ext,
            estimate_presale_outcome_int,
            estimate_inprogress_start,
            estimate_inprogress_end,
            estimate_inprogress_income_before_taxes,
            estimate_inprogress_gross_profitability_before_taxes,
            estimate_inprogress_gross_profit_before_taxes,

backend/app_project/templates/app_project/project_CRUD/partial_create.html
{% load widget_tweaks %}


<form method="post" enctype="multipart/form-data"
      action="{% url 'app_project:project_create' %}"
      data-sub-url="{% url 'app_project:ajax_load_subcat' %}"
      class="js-project-create-form" id="projectForm"
      onsubmit="addspinner(this)"
>
    {% csrf_token %}

    <div class="modal-header">
            <h4>
                {{wording.h1_create_p}}
            </h4>
            <button type="button" class="close " data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true"> <i class="far fa-times close-icon"></i></span>
            </button>
    </div>

    <div class="modal-body">
        {% include 'app_project/partial_form.html' %}
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-outline-danger btn-lg pl-5 pr-5" data-dismiss="modal">{{wording.btn_cancel}}</button>
        <button type="submit"  class="btn btn-success btn-lg pl-5 pr-5" >
            <span>{{wording.btn_create}}</span>
        </button>
    </div>



</form>

backend/app_project/templates/app_project/project_CRUD/partial_delete.html
<form method="post" action="{% url 'app_project:project_delete' item.pk %}" class="js-project-delete-form"
data-redirect="{% url 'app_project:index' %}"
      data-sub-url="{% url 'app_project:ajax_load_subcat' %}" id="projectForm"
      onsubmit="addspinner(this)"
>
  {% csrf_token %}

<div class="modal-header">
        <h4 >
            {{wording.h1_delete_p}}
        </h4>
        <button type="button" class="close " data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"><i class="far fa-times close-icon"></i></span>
        </button>
</div>
    {%  if deletable == True %}
          <div class="modal-body">
            <p class="lead">{{wording.approve_delete}}<strong>{{ item.name }}</strong>?</p>
          </div>
        <div class="modal-footer">
                <button type="button" class="btn btn-outline-danger btn-lg pl-5 pr-5" data-dismiss="modal">{{wording.btn_cancel}}</button>
                <button type="submit" class="btn btn-success btn-lg pl-5 pr-5">{{wording.btn_delete_p}}</button>
        </div>


    {% else %}

                  <div class="modal-body">
                <p class="lead">{{wording.not_deletable}} </p>
              </div>
        <div class="modal-footer">
            <button type="button" class="button-outline button-outline-red" data-dismiss="modal">{{wording.btn_cancel}}</button>
        </div>

    {% endif %}

</form>

backend/app_project/templates/app_project/project_CRUD/partial_update.html
{% load widget_tweaks %}

<form method="post" action="{% url 'app_project:project_update' form.instance.pk %}"
      data-url-estimation="{% url 'app_project:project_update_estimation' form.instance.pk %}" class="js-project-update-form"
      data-sub-url="{% url 'app_project:ajax_load_subcat' %}" id="projectForm"
onsubmit="addspinner(this)"
>
    {% csrf_token %}


    <div class="modal-header">
            <h4 >
                {{wording.h1_update}}
            </h4>
            <button type="button" class="close " data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true"><i class="far fa-times close-icon"></i></span>
            </button>
    </div>

    <div class="modal-body">
            <div class="row mt-2">
                <div class="col-4">
                    {{ form.name_short.label_tag }}
                    {{ form.name_short.errors }}
                    {{ form.name_short }}
                    {{ form.name_short.help_text }}
                </div>
                <div class="col-8">
                    {{ form.name_long.label_tag }}
                    {{ form.name_long.errors }}
                    {{ form.name_long }}
                    {{ form.name_long.help_text }}
                </div>
            </div>
            <div class="row mt-2">
                <div class="col-4">
                    {{ form.subcategory.label_tag }}
                    {{ form.subcategory.errors }}
                    {{ form.subcategory }}
                    {{ form.subcategory.help_text }}
                </div>
                <div class="col-4">
                    {{ form.brand.label_tag }}
                    {{ form.brand.errors }}
                    {{ form.brand }}
                    {{ form.brand.help_text }}
                </div>
                <div class="col-4">
                    {{ form.stage.label_tag }}
                    {{ form.stage.errors }}
                    {{ form.stage }}
                    {{ form.stage.help_text }}
                </div>
            </div>
            <div class="row mt-2">
                <div class="col-3">
                    {{ form.project_start.label_tag }}
                    {{ form.project_start.errors }}
                    {{ form.project_start }}
                    {{ form.project_start.help_text }}
                </div>
                <div class="col-3">
                    {{ form.project_end.label_tag }}
                    {{ form.project_end.errors }}
                    {{ form.project_end }}
                    {{ form.project_end.help_text }}
                </div>
                <div class="col-3" style="display: flex; flex-direction: column; justify-content: space-between;">
                    {{ form.nb_source.label_tag }}
                    {{ form.nb_source.errors }}
                    {{ form.nb_source }}
                    {{ form.nb_source.help_text }}
                </div>
                <div class="col-3">
                    {{ form.nb_format.label_tag }}
                    {{ form.nb_format.errors }}
                    {{ form.nb_format }}
                    {{ form.nb_format.help_text }}
                </div>
            </div>

            <div class="row mt-2">
                <div class="col-12">
                    {{ form.description.label_tag }}
                    {{ form.description.errors }}
                    {{ form.description }}
                    {{ form.description.help_text }}
                </div>
            </div>
            <div class="row mt-2">
                <div class="col-4  product-list ">
                    {{ form.project_products.label_tag }}
                    {% for checkbox in form.project_products %}
                        <div class="form-check">
                            {{ checkbox.tag }}

                             <label class="form-check-label">{{ checkbox.choice_label }}</label>
                        </div>
                    {% endfor %}

                </div>
                <div class="col-4">
                    {{ form.is_editable.label_tag }}
                    {{ form.is_editable.errors }}
                    {{ form.is_editable }}
                    {{ form.is_editable.help_text }}
                </div>
                <div class="col-4">
                    {{ form.commission.label_tag }}
                    {{ form.commission.errors }}
                    {{ form.commission }}
                    {{ form.commission.help_text }}
                </div>
            </div>
    </div>

    <div class="modal-footer">
            <button type="button" class="btn btn-outline-danger btn-lg pl-5 pr-5" data-dismiss="modal">{{wording.btn_cancel}}</button>
            <button type="submit" class="btn btn-success btn-lg pl-5 pr-5" >{{wording.btn_save}}</button>
    </div>


</form>

backend/app_project/templates/app_project/project_CRUD/partial_update_estimation.html
{% load widget_tweaks %}

<form method="post" action="{% url 'app_project:project_update' form.instance.pk %}"
      data-url-estimation="{% url 'app_project:project_update_estimation' form.instance.pk %}" class="js-project-update-estimation-form"
      id="project_est_form"
onsubmit="addspinner(this)">
    {% csrf_token %}


    <div class="modal-header">
            <h4 >
                {{wording.h1_update}}
            </h4>
            <button type="button" class="close " data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true"><i class="far fa-times close-icon"></i></span>
            </button>
    </div>

    <div class="modal-body">
            <div class="row mt-2">
                <div class="col-3">
                    {{ form.estimate_probability.label_tag }}
                    {{ form.estimate_probability.errors }}
                    {{ form.estimate_probability }}
                    {{ form.estimate_probability.help_text }}
                </div>
            </div>
            <div class="row mt-2">
                <div class="col-3" style="display: flex; flex-direction: column; justify-content: space-between;">
                    {{ form.estimate_presale_start.label_tag }}
                    {{ form.estimate_presale_start.errors }}
                    {{ form.estimate_presale_start }}
                    {{ form.estimate_presale_start.help_text }}
                </div>
                <div class="col-3">
                    {{ form.estimate_presale_end.label_tag }}
                    {{ form.estimate_presale_end.errors }}
                    {{ form.estimate_presale_end }}
                    {{ form.estimate_presale_end.help_text }}
                </div>
                <div class="col-3">
                    {{ form.estimate_presale_outcome_ext.label_tag }}
                    {{ form.estimate_presale_outcome_ext.errors }}
                    {{ form.estimate_presale_outcome_ext }}
                    {{ form.estimate_presale_outcome_ext.help_text }}
                </div>
                <div class="col-3">
                    {{ form.estimate_presale_outcome_int.label_tag }}
                    {{ form.estimate_presale_outcome_int.errors }}
                    {{ form.estimate_presale_outcome_int }}
                    {{ form.estimate_presale_outcome_int.help_text }}
                </div>
            </div>
        <hr style="margin: 40px 0;">
            <div class="row mt-2">
                <div class="col-4" style="display: flex; flex-direction: column; justify-content: space-between;">
                    {{ form.estimate_inprogress_start.label_tag }}
                    {{ form.estimate_inprogress_start.errors }}
                    {{ form.estimate_inprogress_start }}
                    {{ form.estimate_inprogress_start.help_text }}
                </div>
                <div class="col-4" style="display: flex; flex-direction: column; justify-content: space-between;">
                    {{ form.estimate_inprogress_end.label_tag }}
                    {{ form.estimate_inprogress_end.errors }}
                    {{ form.estimate_inprogress_end }}
                    {{ form.estimate_inprogress_end.help_text }}
                </div>
                <div class="col-4" style="display: flex; flex-direction: column; justify-content: space-between;">
                    {{ form.estimate_inprogress_income_before_taxes.label_tag }}
                    {{ form.estimate_inprogress_income_before_taxes.errors }}
                    {{ form.estimate_inprogress_income_before_taxes }}
                    {{ form.estimate_inprogress_income_before_taxes.help_text }}
                </div>
            </div>
            <div class="row mt-2">
                <div class="col-3">
                    {{ form.estimate_inprogress_gross_profitability_before_taxes.label_tag }}
                    {{ form.estimate_inprogress_gross_profitability_before_taxes.errors }}
                    {{ form.estimate_inprogress_gross_profitability_before_taxes }}
                    {{ form.estimate_inprogress_gross_profitability_before_taxes.help_text }}
                </div>
                <div class="col-3"  style="display: flex; flex-direction: column; justify-content: space-between;">
                    {{ form.estimate_inprogress_gross_profit_before_taxes.label_tag }}
                    {{ form.estimate_inprogress_gross_profit_before_taxes.errors }}
                    {{ form.estimate_inprogress_gross_profit_before_taxes }}
                    {{ form.estimate_inprogress_gross_profit_before_taxes.help_text }}
                </div>
                <div class="col-3">
                    {{ form.estimate_inprogress_project_profitability_before_taxes.label_tag }}
                    {{ form.estimate_inprogress_project_profitability_before_taxes.errors }}
                    {{ form.estimate_inprogress_project_profitability_before_taxes }}
                    {{ form.estimate_inprogress_project_profitability_before_taxes.help_text }}
                </div>
                <div class="col-3"  style="display: flex; flex-direction: column; justify-content: space-between;">
                    {{ form.estimate_inprogress_project_profit_before_taxes.label_tag }}
                    {{ form.estimate_inprogress_project_profit_before_taxes.errors }}
                    {{ form.estimate_inprogress_project_profit_before_taxes }}
                    {{ form.estimate_inprogress_project_profit_before_taxes.help_text }}
                </div>
            </div>

    </div>

    <div class="modal-footer">
            <button type="button" class="btn btn-outline-danger btn-lg pl-5 pr-5" data-dismiss="modal">{{wording.btn_cancel}}</button>
            <button type="submit" class="btn btn-success btn-lg pl-5 pr-5">{{wording.btn_save}}</button>
    </div>


</form>

backend/app_project/templates/app_project/project_CRUD/subcategory_dropdown_list_options.html
<option value="">---------</option>
{% for sub in subcategory %}
<option value="{{ sub.pk }}">{{ sub.name }}</option>
{% endfor %}