backend/app_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'app_project'
urlpatterns = [
    # path('', views.index, name='index'),
    # path('project/<pk>/', views.project, name='project'),
    path('api/', views.project_list),
    path('api/<int:pk>/', views.project_detail),
    path('api/extra/', views.project_extra),
    path('api/statistics/<int:pk>/', views.project_statistics),
    path('api/history/', views.project_history),
    path('api/excel/', views.excel_export),

    path('api/team_list/<int:pk>/', views.project_team_list),
    path('api/team/<int:pk>/', views.project_team_detail),

    path('api/service_list/<int:pk>/', views.project_service_list),
    path('api/service/<int:pk>/', views.project_service_detail),

    path('api/period_list/<int:pk>/', views.project_period_list),
    path('api/period/<int:pk>/', views.project_period_detail),

    path('api/report_list/<int:pk>/', views.project_report_list),
    path('api/report/<int:pk>/', views.project_report_detail),





    # path('project/<pk>/', views.project, name='project'),
    # path('project_create/', views.project_create, name='project_create'),
    # path('project_update/<pk>/', views.project_update, name='project_update'),
    # path('project_update_estimation/<pk>/', views.project_update_estimation, name='project_update_estimation'),
    # path('project_delete/<pk>/', views.project_delete, name='project_delete'),
    #
    # path('project/history', views.project_history, name='project_history'),
    #
    # path('ajax/load-subcat/', views.load_subcat, name='ajax_load_subcat'),
    #
    # path('create_period/<projectpk>/', views.create_period, name='create_period'),
    # path('update_period/<pk>/', views.update_period, name='update_period'),
    # path('delete_period/<pk>/', views.delete_period, name='delete_period'),
    #
    # path('service_create/<projectpk>/', views.service_create, name='service_create'),
    # path('service_update/<pk>/', views.service_update, name='service_update'),
    # path('service_delete/<pk>/', views.service_delete, name='service_delete'),
    #
    # path('report_create/<projectpk>/<periodpk>', views.report_create, name='report_create'),
    # path('report_update/<pk>/<projectpk>', views.report_update, name='report_update'),
    # path('report_delete/<pk>/', views.report_delete, name='report_delete'),
    #
    # path('team_create/<projectpk>/', views.team_create, name='team_create'),
    # path('team_update/<pk>/', views.team_update, name='team_update'),
    # path('team_delete/<pk>/', views.team_delete, name='team_delete'),
    #
    # path('excel_export/', views.excel_export, name='excel_export'),

]

backend/app_transaction/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'app_transaction'
urlpatterns = [
    # path('', views.transaction_index, name='index'),
    path('api/', views.transaction_list),
    path('api/<int:pk>/', views.transaction_detail),
    path('api/history/', views.api_transaction_history),
    path('api/excel/', views.api_transaction_excel),
    path('api/extra/', views.api_transaction_extra, ),


    path('transactions/create_project/<projectpk>', views.transaction_create_project, name='transaction_create_project'),
    path('transactions/update_project/<pk>', views.transaction_update_project, name='transaction_update_project'),
    path('transactions/delete_project/<pk>', views.transaction_delete_project, name='transaction_delete_project'),

    path('transactions/create_project_period/<projectpk>/<periodpk>', views.transaction_create_project_period,
         name='transaction_create_project_period'),
    path('transactions/update_project_period/<pk>/<projectpk>', views.transaction_update_project_period, name='transaction_update_project_period'),
    path('transactions/delete_project_period/<pk>', views.transaction_delete_project_period, name='transaction_delete_project_period'),



    path('ajax/load-purpose/', views.load_purpose, name='ajax_load_purpose'),
    path('ajax/subcontractor-info/', views.subcontractor_info, name='ajax_subcontractor_info'),
    path('ajax/account-info/', views.account_info, name='ajax_account_info'),
    path('ajax/mycompany-info/', views.mycompany_info, name='ajax_mycompany_info'),
    path('ajax/list_saver/', views.list_saver, name='ajax_list_saver'),

    path('transaction_docs/<pk>/', views.transaction_docs, name='transaction_docs'),

    # path('transactions/create/', views.transaction_create, name='transaction_create'),
    # path('transactions/save/', views.transaction_save, name='transaction_save'),
    # path('transactions/update/<pk>', views.transaction_update, name='transaction_update'),
    # path('transactions/delete/<pk>', views.transaction_delete, name='transaction_delete'),

    # path('transfer/create/', views.transfer_create, name='transfer_create'),
    # path('transfer/save/', views.transfer_save, name='transfer_save'),
    # path('transfer/update/<pk>', views.transfer_update, name='transfer_update'),
    # path('transfer/delete/<pk>', views.transfer_delete, name='transfer_delete'),
]

backend/fins/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path('', include('app_about.urls')),
    # path('app/', include('app_frontend.urls')),
    path('app/', RedirectView.as_view(url='https://finsapp.ru'), name='app'),
    path('auth/', include('app_auth.urls')),
    path('signup/', include('app_signup.urls')),
    path('setup/', include('app_setup.urls')),
    path('dashboard/', include('app_dashboard.urls')),
    path('projects/', include('app_project.urls')),
    path('transactions/', include('app_transaction.urls')),
    path('docs/', include('app_docs.urls')),
    path('reports/', include('app_reports.urls')),
    path('admin/', admin.site.urls, name='admin'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # import debug_toolbar
    # urlpatterns = [
    #     path('__debug__/', include(debug_toolbar.urls)),
    #
    #     # For django versions before 2.0:
    #     # url(r'^__debug__/', include(debug_toolbar.urls)),
    #
    # ] + urlpatterns

backend/app_project/views/excel.py
from app_project.decorators import *
from app_auth.decorators import access_company_level
from django.contrib.auth.decorators import login_required
from app_project import models as app_project_models
from app_project.tools import filter_extra_data
from app_project.filters import ProjectsFilter
from django.http import HttpResponse
import xlwt
import datetime
from django.contrib.sites.models import Site


@login_required
@access_company_level
@access_app_projects_list
def excel_export(request, get_access_all):
    project_filter_qs = request.session['project_filter_qs']
    queryset = get_access_all().filter(pk__in=project_filter_qs)

    filter = ProjectsFilter(request.GET, queryset=queryset)
    filter = filter_extra_data(filter)

    response = HttpResponse(content_type='application/ms-excel')
    filename = str(Site.objects.all()[0]) + '_projects_' + str(datetime.datetime.now())
    response['Content-Disposition'] = 'attachment; filename=' + filename + '.xls'
    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet("Проекты")

    #table header
    row_num = 0
    model = app_project_models.Project
    columns = [
        (str(model._meta.get_field('name').verbose_name), 4000),
        (str(model._meta.get_field('name_short').verbose_name), 4000),
        (str(model._meta.get_field('brand').verbose_name), 4000),
        (str(model._meta.get_field('category').verbose_name), 4000),
        (str(model._meta.get_field('subcategory').verbose_name), 4000),
        (str(model._meta.get_field('work_format').verbose_name), 4000),
        (str(model._meta.get_field('agreement_format').verbose_name), 4000),
        (str(model._meta.get_field('commission').verbose_name), 4000),
        (str(model._meta.get_field('stage').verbose_name), 4000),
        (str(model._meta.get_field('project_start').verbose_name), 4000),
        (str(model._meta.get_field('project_end').verbose_name), 4000),
        ("Лидер проекта", 4000),
        ("Команда проекта", 4000),
        ("Юниты", 4000),
        ("Выручка проекта (в основной валюте)", 4000),
        ("Внешние расходы проекта (в основной валюте)", 4000),
        ("Валовая прибыль проекта (в основной валюте)", 4000),
        ("РВП проекта (в основной валюте)", 4000),

        (str(model._meta.get_field('nb_source').verbose_name), 4000),
        (str(model._meta.get_field('nb_format').verbose_name), 4000),
        (str(model._meta.get_field('estimate_probability').verbose_name), 4000),
        (str(model._meta.get_field('estimate_presale_start').verbose_name), 4000),
        (str(model._meta.get_field('estimate_presale_end').verbose_name), 4000),
        (str(model._meta.get_field('estimate_presale_outcome_ext').verbose_name), 4000),
        (str(model._meta.get_field('estimate_presale_outcome_int').verbose_name), 4000),
        (str(model._meta.get_field('estimate_inprogress_start').verbose_name), 4000),
        (str(model._meta.get_field('estimate_inprogress_end').verbose_name), 4000),
        (str(model._meta.get_field('estimate_inprogress_income_before_taxes').verbose_name), 4000),
        (str(model._meta.get_field('estimate_inprogress_gross_profitability_before_taxes').verbose_name), 4000),
        (str(model._meta.get_field('estimate_inprogress_gross_profit_before_taxes').verbose_name), 4000),
        (str(model._meta.get_field('estimate_inprogress_project_profitability_before_taxes').verbose_name), 4000),
        (str(model._meta.get_field('estimate_inprogress_project_profit_before_taxes').verbose_name), 4000),



        (str(model._meta.get_field('created_at').verbose_name), 4000),
        (str(model._meta.get_field('created_by').verbose_name), 4000),
        (str(model._meta.get_field('modified_at').verbose_name), 4000),
        (str(model._meta.get_field('modified_by').verbose_name), 4000),



    ]
    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    #rows
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num][0], font_style)
        # set column width
        ws.col(col_num).width = columns[col_num][1]

    font_style = xlwt.XFStyle()
    font_style.alignment.wrap = 1



    for obj in filter.qs:


        if obj.category == None:
            category = ''
        else:
            category = obj.category.name

        if obj.subcategory == None:
            subcategory = ''
        else:
            subcategory = obj.subcategory.name


        if obj.work_format == None:
            work_format = ''
        else:
            work_format = obj.get_work_format_display()

        if obj.agreement_format == None:
            agreement_format = ''
        else:
            agreement_format = obj.get_agreement_format_display()

        if obj.stage == None:
            stage = ''
        else:
            stage = obj.get_stage_display()

        if obj.brand == None:
            brand = ''
        else:
            brand = obj.brand.name

        if obj.project_start == None:
            project_start = ''
        else:
            project_start = obj.project_start.strftime("%d/%m/%Y")

        if obj.project_end == None:
            project_end = ''
        else:
            project_end = obj.project_end.strftime("%d/%m/%Y")


        if obj.leader == None:
            leader = ''
        else:
            leader = str(obj.leader)

        if obj.team == None:
            team = ''
        else:
            team = str(obj.team)

        if obj.units == None:
            units = ''
        else:
            units = str(obj.units)



        if obj.nb_source == None:
            nb_source = ''
        else:
            nb_source = obj.nb_source.name

        if obj.nb_format == None:
            nb_format = ''
        else:
            nb_format = obj.nb_format.name

        if obj.estimate_probability == None:
            estimate_probability = ''
        else:
            estimate_probability = obj.estimate_probability

        if obj.estimate_presale_start == None:
            estimate_presale_start = ''
        else:
            estimate_presale_start = obj.estimate_presale_start.strftime("%d/%m/%Y")

        if obj.estimate_presale_end == None:
            estimate_presale_end = ''
        else:
            estimate_presale_end = obj.estimate_presale_end.strftime("%d/%m/%Y")

        if obj.estimate_presale_outcome_ext == None:
            estimate_presale_outcome_ext = ''
        else:
            estimate_presale_outcome_ext = obj.estimate_presale_outcome_ext

        if obj.estimate_presale_outcome_int == None:
            estimate_presale_outcome_int = ''
        else:
            estimate_presale_outcome_int = obj.estimate_presale_outcome_int

        if obj.estimate_inprogress_start == None:
            estimate_inprogress_start = ''
        else:
            estimate_inprogress_start = obj.estimate_inprogress_start.strftime("%d/%m/%Y")

        if obj.estimate_inprogress_end == None:
            estimate_inprogress_end = ''
        else:
            estimate_inprogress_end = obj.estimate_inprogress_end.strftime("%d/%m/%Y")

        if obj.estimate_inprogress_income_before_taxes == None:
            estimate_inprogress_income_before_taxes = ''
        else:
            estimate_inprogress_income_before_taxes = obj.estimate_inprogress_income_before_taxes

        if obj.estimate_inprogress_gross_profitability_before_taxes == None:
            estimate_inprogress_gross_profitability_before_taxes = ''
        else:
            estimate_inprogress_gross_profitability_before_taxes = obj.estimate_inprogress_gross_profitability_before_taxes

        if obj.estimate_inprogress_gross_profit_before_taxes == None:
            estimate_inprogress_gross_profit_before_taxes = ''
        else:
            estimate_inprogress_gross_profit_before_taxes = obj.estimate_inprogress_gross_profit_before_taxes

        if obj.estimate_inprogress_project_profitability_before_taxes == None:
            estimate_inprogress_project_profitability_before_taxes = ''
        else:
            estimate_inprogress_project_profitability_before_taxes = obj.estimate_inprogress_project_profitability_before_taxes

        if obj.estimate_inprogress_project_profit_before_taxes == None:
            estimate_inprogress_project_profit_before_taxes = ''
        else:
            estimate_inprogress_project_profit_before_taxes = obj.estimate_inprogress_project_profit_before_taxes


        if obj.created_at == None:
            created_at = ''
        else:
            created_at = obj.created_at.replace(tzinfo=None).strftime("%d/%m/%Y")

        if obj.created_by == None:
            created_by = ''
        else:
            created_by = str(obj.created_by)

        if obj.modified_at == None:
            modified_at = ''
        else:
            modified_at = obj.modified_at.replace(tzinfo=None).strftime("%d/%m/%Y")

        if obj.modified_by == None:
            modified_by = ''
        else:
            modified_by = str(obj.modified_by)









        row_num += 1
        row = [
            obj.name,
            obj.name_short,
            brand,
            category,
            subcategory,
            work_format,
            agreement_format,
            obj.commission,
            stage,
            project_start,
            project_end,
            leader,
            team,
            units,
            obj.income,
            obj.outcome_ext,
            obj.gross_profit,
            obj.gross_profitability,




            nb_source,
            nb_format,
            estimate_probability,
            estimate_presale_start,
            estimate_presale_end,
            estimate_presale_outcome_ext,
            estimate_presale_outcome_int,
            estimate_inprogress_start,
            estimate_inprogress_end,
            estimate_inprogress_income_before_taxes,
            estimate_inprogress_gross_profitability_before_taxes,
            estimate_inprogress_gross_profit_before_taxes,

backend/app_project/templates/app_project/new/index_project.html
{% extends 'base_app.html' %}
{% load static %}
{% load widget_tweaks %}
{% load get_verbose_name %}

{% block header %}
    <div style="white-space: nowrap;">
        <div class="d-flex align-items-center">
            <a href="#" class=" px-4 py-4 border-right back-btn"><h4 ><i class="fal fa-chevron-left"></i></h4></a>
            <h1 class="ml-3 mt-1">
                {{ pk }}
                <div id="project_name">{% include 'app_project/project_card/partial_project_name.html' %}</div>
            </h1>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="block-section-3">




    <div class="row mb-5">
        <div class="col-12">
            <v-statictics :id={{ pk }} ref="statictics"></v-statictics>


        </div>
    </div>
{##}
{##}
{##}
{##}
{#    {% if project.work_format != 1 %}#}
{#    <div class="row  mb-5" style="overflow-y: scroll;">#}
{#        <div class="col-12">#}
{#            <div class="d-flex justify-content-between align-items-start  mb-4">#}
{#                <h4 class="mb-3">{{wording.h1_list}}</h4>#}
{#                {% if project.is_editable == True or user_can_block == 0 %}#}
{#                    <button type="submit" class="js-create-transaction btn btn-sm btn-primary" data-url="{% url 'app_transaction:transaction_create_project' project.pk %}">#}
{#                        {{wording.btn_add}}#}
{#                    </button>#}
{#                {% endif %}#}
{##}
{#            </div>#}
{##}
{#            <table id="transactions_list" class="table">#}
{#                <thead>#}
{#                    {% include 'app_transaction/in_project/partial_list_header.html' %}#}
{#                </thead>#}
{#                <tbody>#}
{#                    {% include 'app_transaction/in_project/partial_list_in_projects.html' %}#}
{#                </tbody>#}
{#            </table>#}
{#        </div>#}
{#    </div>#}
{#    {% endif %}#}
{##}
{##}
{##}
{#    {% if project.work_format == 1 %}#}
{##}
{#        <div class="row mb-5  mr-2" style="overflow-y: scroll;">#}
{#            <div class="col-12">#}
{##}
{#                <div class="d-flex justify-content-between align-items-start  mb-4">#}
{#                    <h4>{{wording.h1_period}}</h4>#}
{#                    {% if project.is_editable == True or user_can_block == 0 %}#}
{#                        <button type="submit" class="js-create-period btn  btn-sm btn-primary" data-url="{% url 'app_project:create_period' project.pk %}">#}
{#                            {{wording.btn_add2}}#}
{#                        </button>#}
{#                    {% endif %}#}
{#                </div>#}
{#                <div id="report_periods">#}
{#                    {% include 'app_project/project_card/partial_list_periods.html' %}#}
{#                </div>#}
{##}
{#            </div>#}
{#        </div>#}
{#    {% endif %}#}
{##}
{##}
    <div class="row mb-4 mr-3">
        <div class="col-6" >
            <div class="border mx-1 px-5 py-5 h-100">
                <v-base-show :id={{ pk }} ref="showBase" v-on:update-base="updateBase"></v-base-show>
            </div>
        </div>
        <div class="col-6" >
            <div class="border mx-1 px-5 py-5 h-100">
                <v-estimate-show :id={{ pk }} ref="showEstimate" v-on:update-estimate="updateEstimate"></v-estimate-show>
            </div>
        </div>
{#        <div class="col-6">#}
{#            <div class="border mx-1 px-5 py-5 h-100">#}
{##}
{#                <div class="d-flex justify-content-between align-items-start">#}
{##}
{#                    <h4  class="mb-5">Предпродажная оценка</h4>#}
{#                    {% if project.is_editable == True or user_can_block == 0 %}#}
{#                        <button type="button"#}
{#                          class="js-update-estimation-project  btn  btn-sm btn-primary  mt-1"#}
{#                          data-url="{% url 'app_project:project_update_estimation' pk %}">#}
{#    <!--                        {{wording.btn_est}}-->#}
{#                            <i class="far fa-pencil"></i>#}
{##}
{#                        </button>#}
{#                    {% endif %}#}
{#                </div>#}
{#               <div id="partial_project_estimation">#}
{#                    {% include 'app_project/project_card/partial_project_estimation.html' %}#}
{#               </div>#}
{#            </div>#}
{#        </div>#}
    </div>
{##}
{##}
{##}
{##}
{##}
{##}
{##}
{##}
{##}
{##}
{##}
{#    <div class="row mb-4 mr-3">#}
{#        {% if project.work_format == 1 %}#}
{#                <div class="col-12 ">#}
{#                    <div class="border mx-1 px-5 py-5  h-100">#}
{#                        <div class="d-flex justify-content-between align-items-start  mb-4">#}
{#                            <h4>{{wording.h1_service}}</h4>#}
{#                            {% if project.is_editable == True or user_can_block == 0 %}#}
{#                                <button type="submit" class="js-create-service btn  btn-sm btn-primary" data-url="{% url 'app_project:service_create' project.pk %}">#}
{#                                    <i class="fal fa-plus"></i>#}
{#    <!--                                {{wording.btn_add3}}-->#}
{#                                </button>#}
{#                            {% endif %}#}
{#                        </div>#}
{#                        <table class="table mb-0">#}
{#                            <thead>#}
{#                                <th>Название</th>#}
{#                                <th>Стоимость часа</th>#}
{#                                <th></th>#}
{##}
{#                            </thead>#}
{#                            <tbody id="services">#}
{#                                {% include 'app_project/project_card/partial_list_services.html' %}#}
{#                            </tbody>#}
{#                        </table>#}
{#                    </div>#}
{#                </div>#}
{#        {% endif %}#}
{##}
{##}
{##}
{##}
{##}
{##}
{#    </div>#}
{##}
{##}
    <div class="row mb-5 mr-3">
        <div class="col-6">
            <v-team-show  :id={{ pk }} ref="showTeam" v-on:create-team='createTeam' v-on:update-team="editTeam" v-on:delete-team="deleteTeam"></v-team-show>
        </div>
        <div class="col-6">

            <div class="border mx-1 px-5 py-5  h-100">

                <v-docs :id={{ pk }}></v-docs>
            </div>
        </div>
    </div>
{##}
{##}
{##}
{#    {%  if project.is_deletable == True %}#}
{#        {% if project.is_editable == True or user_can_block == 0 %}#}
{#            <div class="row mb-5">#}
{#                <div class="col-12">#}
{#<!--                    <hr>-->#}
{#                    <button type="button"#}
{#                      class="js-delete-project btn btn-outline-danger mt-4"#}
{#                      data-url="{% url 'app_project:project_delete' pk %}">#}
{#                        {{wording.btn_delete_p}}#}
{#                    </button>#}
{#                </div>#}
{#            </div>#}
{#        {% endif %}#}
{#    {% endif %}#}
{##}
{##}
{##}
{#</div>#}
{##}
{##}
{#<div class="modal fade" id="modal-global">#}
{#    <div class="modal-dialog">#}
{#          <div class="modal-content">#}
{#         </div>#}
{#    </div>#}
{#</div>#}

    <!--Modals-->
    <v-base-update :id={{ pk }} ref="updateBase" v-on:update-base="updateProject" :wording="wording"></v-base-update>
    <v-estimate-update :id={{ pk }} ref="updateEstimate" v-on:update-estimate="updateProject" :wording="wording"></v-estimate-update>
    <v-team-create :id={{ pk }} ref="createTeam" v-on:update-team="updateTeam" :wording="wording"></v-team-create>
    <v-team-update :id={{ pk }} ref="updateTeam" v-on:update-team="updateTeam" :wording="wording"></v-team-update>
    <v-team-delete :id={{ pk }} ref="deleteTeam" v-on:update-team="updateTeam" :wording="wording"></v-team-delete>


    <!--End-->

{% endblock %}



{% block javascript %}
    <script type='text/javascript' src="{% static 'project/js/app.js' %}"></script>
    <script type='text/javascript' src="{% static 'project/js/chunk-vendors.js' %}"></script>
{% endblock %}